version: '3.9'

services:
    clickhouse-db:
      container_name: clickhouse-db
      image: clickhouse/clickhouse-server:23.3.20.27
      restart: on-failure
      ports:
        - "8123:8123"
        - "9000:9000"
      environment:
        - CLICKHOUSE_DB=data_source
      volumes:
        - clickhouse-volume:/var/lib/clickhouse
      networks:
        - tutorial 
    postgres-db:
      container_name: postgres-dwh
      image: postgres:15.2
      restart: on-failure
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=dwh
      ports:
        - "5432:5432"
      networks:
        - tutorial 
      volumes:
        - ./pg_data:/var/lib/postgresql/data


networks:
  tutorial:
    external: true

volumes:
  clickhouse-volume:
    external: true